### ISSUE TITLE
Chat sometimes freezes

### ISSUE THREAD

**Issue by Jujucan** [sparcut/BetterYTG#7]
The chat sometimes stops and does not auto-scroll beyond the blue arrow.
You have to manually press it for chat to move on.
Some kind of chat auto scroll would make this perfect.
Other than this I love this extension. It works when nothing else would for me so good work.

**Comment by sparcut** [comment]
Hmm, the chat will stop auto-scroll when the cursor is in the chat region. When the cursor moves out, the chat should resume auto-scrolling.

Might this be the problem you are having?

**Comment by sparcut** [comment]
@Jujucan Any update on this?

**Comment by sparcut** [comment]
Closed due to inactivity.
